#include "test_prelude.hpp"
import forge.vm.wasm.interpret.allocator;
import forge.vm.wasm.interpret.stack_elem;
import forge.vm.wasm.interpret.utils;
import forge.vm.wasm.interpret.backend;
#define FORGE_VM_WASM_INTERPRET_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_INTERPRET_TEST_FILE spec_br_if_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm::interpret;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <br_if_0_wasm>", "[br_if_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-i32")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-i64")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-f32")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-f64")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i32-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i64-value")->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-f32-value")->to_f32()) == UINT32_C(1077936128)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-f64-value")->to_f64()) == UINT64_C(4616189618054758400)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-first", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-first", UINT32_C(1))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-mid", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-mid", UINT32_C(1))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-block-last", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-block-last", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-first-value", UINT32_C(0))->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-first-value", UINT32_C(1))->to_ui32() == UINT32_C(10)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-mid-value", UINT32_C(0))->to_ui32() == UINT32_C(21)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-mid-value", UINT32_C(1))->to_ui32() == UINT32_C(20)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-last-value", UINT32_C(0))->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-last-value", UINT32_C(1))->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-first", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-first", UINT32_C(1))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-mid", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-mid", UINT32_C(1))->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-loop-last", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-loop-last", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_if-cond")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value-cond", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value-cond", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_table-index")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value-index")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-return-value")->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-cond", UINT32_C(0))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-cond", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-then", UINT32_C(0), UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-then", UINT32_C(4), UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-then", UINT32_C(0), UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-then", UINT32_C(4), UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-else", UINT32_C(0), UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-else", UINT32_C(3), UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-else", UINT32_C(0), UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-if-else", UINT32_C(3), UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first", UINT32_C(0))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first", UINT32_C(1))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-second", UINT32_C(0))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-second", UINT32_C(1))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-cond")->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-first")->to_ui32() == UINT32_C(12)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-mid")->to_ui32() == UINT32_C(13)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-last")->to_ui32() == UINT32_C(14)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-func")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-first")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-mid")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-last")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.set-value", UINT32_C(0))->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.set-value", UINT32_C(1))->to_ui32() == UINT32_C(17)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.tee-value", UINT32_C(0))->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.tee-value", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-global.set-value", UINT32_C(0))->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-global.set-value", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-load-address")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loadN-address")->to_ui32() == UINT32_C(30)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-store-address")->to_ui32() == UINT32_C(30)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-store-value")->to_ui32() == UINT32_C(31)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-storeN-address")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-storeN-value")->to_ui32() == UINT32_C(33)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "as-unary-operand")->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-left")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-right")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-test-operand")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-left")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-right")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-memory.grow-size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-block-value", UINT32_C(0))->to_ui32() == UINT32_C(21)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-block-value", UINT32_C(1))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br-value", UINT32_C(0))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br-value", UINT32_C(1))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value", UINT32_C(0))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value", UINT32_C(1))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value-cond", UINT32_C(0))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value-cond", UINT32_C(1))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value", UINT32_C(0))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value", UINT32_C(1))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value-index", UINT32_C(0))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value-index", UINT32_C(1))->to_ui32() == UINT32_C(9)));
}

BACKEND_TEST_CASE( "Testing wasm <br_if_1_wasm>", "[br_if_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_10_wasm>", "[br_if_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.10.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_11_wasm>", "[br_if_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.11.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_12_wasm>", "[br_if_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.12.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_13_wasm>", "[br_if_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.13.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_14_wasm>", "[br_if_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_15_wasm>", "[br_if_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_16_wasm>", "[br_if_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_17_wasm>", "[br_if_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_18_wasm>", "[br_if_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_19_wasm>", "[br_if_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.19.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_2_wasm>", "[br_if_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.2.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_20_wasm>", "[br_if_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.20.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_21_wasm>", "[br_if_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.21.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_22_wasm>", "[br_if_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.22.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_23_wasm>", "[br_if_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.23.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_24_wasm>", "[br_if_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.24.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_25_wasm>", "[br_if_25_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.25.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_26_wasm>", "[br_if_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.26.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_27_wasm>", "[br_if_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.27.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_28_wasm>", "[br_if_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.28.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_29_wasm>", "[br_if_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.29.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_3_wasm>", "[br_if_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.3.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_4_wasm>", "[br_if_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_5_wasm>", "[br_if_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.5.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_6_wasm>", "[br_if_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.6.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_7_wasm>", "[br_if_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.7.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_8_wasm>", "[br_if_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.8.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_if_9_wasm>", "[br_if_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br_if.9.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
