#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_br_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <br_0_wasm>", "[br_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-i32")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-i64")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-f32")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "type-f64")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i32-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i64-value")->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-f32-value")->to_f32()) == UINT32_C(1077936128)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-f64-value")->to_f64()) == UINT64_C(4616189618054758400)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-block-first")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-block-mid")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-block-last")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-value")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-first")->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-mid")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-last")->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br-value")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_if-cond")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value")->to_ui32() == UINT32_C(8)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value-cond")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_table-index")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value")->to_ui32() == UINT32_C(10)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value-index")->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-return-value")->to_ui64() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-cond")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-then", UINT32_C(1), UINT32_C(6))->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-then", UINT32_C(0), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-else", UINT32_C(0), UINT32_C(6))->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-else", UINT32_C(1), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first", UINT32_C(0), UINT32_C(6))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first", UINT32_C(1), UINT32_C(6))->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-second", UINT32_C(0), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-second", UINT32_C(1), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-cond")->to_ui32() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-first")->to_ui32() == UINT32_C(12)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-mid")->to_ui32() == UINT32_C(13)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-last")->to_ui32() == UINT32_C(14)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-func")->to_ui32() == UINT32_C(20)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-first")->to_ui32() == UINT32_C(21)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-mid")->to_ui32() == UINT32_C(22)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-last")->to_ui32() == UINT32_C(23)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.set-value")->to_ui32() == UINT32_C(17)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.tee-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-global.set-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-load-address")->to_f32()) == UINT32_C(1071225242)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loadN-address")->to_ui64() == UINT32_C(30)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-store-address")->to_ui32() == UINT32_C(30)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-store-value")->to_ui32() == UINT32_C(31)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-storeN-address")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-storeN-value")->to_ui32() == UINT32_C(33)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-unary-operand")->to_f32()) == UINT32_C(1079613850)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-left")->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-right")->to_ui64() == UINT32_C(45)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-test-operand")->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-left")->to_ui32() == UINT32_C(43)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-right")->to_ui32() == UINT32_C(42)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-convert-operand")->to_ui32() == UINT32_C(41)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-memory.grow-size")->to_ui32() == UINT32_C(40)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-block-value")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br-value")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_if-value-cond")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "nested-br_table-value-index")->to_ui32() == UINT32_C(9)));
}

BACKEND_TEST_CASE( "Testing wasm <br_1_wasm>", "[br_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_10_wasm>", "[br_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.10.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_11_wasm>", "[br_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.11.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_12_wasm>", "[br_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.12.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_13_wasm>", "[br_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.13.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_14_wasm>", "[br_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_15_wasm>", "[br_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_16_wasm>", "[br_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_17_wasm>", "[br_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_18_wasm>", "[br_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_19_wasm>", "[br_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.19.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_2_wasm>", "[br_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.2.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_20_wasm>", "[br_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.20.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_3_wasm>", "[br_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.3.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_4_wasm>", "[br_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_5_wasm>", "[br_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.5.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_6_wasm>", "[br_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.6.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_7_wasm>", "[br_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.7.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_8_wasm>", "[br_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.8.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <br_9_wasm>", "[br_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "br.9.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
