#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_break_drop_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <break-drop_0_wasm>", "[break-drop_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "break-drop.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "br")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "br_if")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "br_table")));
}
