#include "test_prelude.hpp"
import forge.vm.wasm.backend;
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_call_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <call_0_wasm>", "[call_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i32")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i64")->to_ui64() == UINT32_C(356)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-f32")->to_f32()) == UINT32_C(1165172736)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-f64")->to_f64()) == UINT64_C(4660882566700597248)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-first-i32")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-first-i64")->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-first-f32")->to_f32()) == UINT32_C(1068037571)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-first-f64")->to_f64()) == UINT64_C(4610064722561534525)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-second-i32")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-second-i64")->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-second-f32")->to_f32()) == UINT32_C(1107296256)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-second-f64")->to_f64()) == UINT64_C(4634211053438658150)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac", UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac", UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac", UINT64_C(5))->to_ui64() == UINT32_C(120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac", UINT64_C(25))->to_ui64() == UINT32_C(7034535277573963776)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-acc", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-acc", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-acc", UINT64_C(5), UINT64_C(1))->to_ui64() == UINT32_C(120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-acc", UINT64_C(25), UINT64_C(1))->to_ui64() == UINT32_C(7034535277573963776)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib", UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib", UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib", UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib", UINT64_C(5))->to_ui64() == UINT32_C(8)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib", UINT64_C(20))->to_ui64() == UINT32_C(10946)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT64_C(0))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT64_C(1))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT64_C(100))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT64_C(77))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT64_C(0))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT64_C(1))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT64_C(200))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT64_C(77))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-mid")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-condition")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-first")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-first")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-first")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-mid")->to_ui32() == UINT32_C(2)));
   BOOST_CHECK_THROW(bkend("env", "as-call_indirect-last"), std::exception);
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-first")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-last")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-memory.grow-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-return-value")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-drop-operand")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br-value")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.set-value")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.tee-value")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-global.set-value")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-load-operand")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-unary-operand")->to_f32()) == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-left")->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-right")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-test-operand")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-left")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-right")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-convert-operand")->to_ui64() == UINT32_C(1)));
}

BACKEND_TEST_CASE( "Testing wasm <call_1_wasm>", "[call_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_10_wasm>", "[call_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.10.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_11_wasm>", "[call_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.11.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_12_wasm>", "[call_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.12.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_13_wasm>", "[call_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.13.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_14_wasm>", "[call_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_15_wasm>", "[call_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_16_wasm>", "[call_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_17_wasm>", "[call_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_18_wasm>", "[call_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_2_wasm>", "[call_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.2.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_3_wasm>", "[call_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.3.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_4_wasm>", "[call_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_5_wasm>", "[call_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.5.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_6_wasm>", "[call_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.6.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_7_wasm>", "[call_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.7.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_8_wasm>", "[call_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.8.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_9_wasm>", "[call_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call.9.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
