#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_call_indirect_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <call_indirect_0_wasm>", "[call_indirect_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i32")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-i64")->to_ui64() == UINT32_C(356)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-f32")->to_f32()) == UINT32_C(1165172736)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-f64")->to_f64()) == UINT64_C(4660882566700597248)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-index")->to_ui64() == UINT32_C(100)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-first-i32")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-first-i64")->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-first-f32")->to_f32()) == UINT32_C(1068037571)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-first-f64")->to_f64()) == UINT64_C(4610064722561534525)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-second-i32")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "type-second-i64")->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "type-second-f32")->to_f32()) == UINT32_C(1107296256)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "type-second-f64")->to_f64()) == UINT64_C(4634211053438658150)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch", UINT32_C(5), UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch", UINT32_C(5), UINT64_C(5))->to_ui64() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch", UINT32_C(12), UINT64_C(5))->to_ui64() == UINT32_C(120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch", UINT32_C(13), UINT64_C(5))->to_ui64() == UINT32_C(8)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch", UINT32_C(20), UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_CHECK_THROW(bkend("env", "dispatch", UINT32_C(0), UINT64_C(2)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch", UINT32_C(15), UINT64_C(2)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch", UINT32_C(29), UINT64_C(2)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch", UINT32_C(4294967295), UINT64_C(2)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch", UINT32_C(1213432423), UINT64_C(2)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i64", UINT32_C(5))->to_ui64() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i64", UINT32_C(12))->to_ui64() == UINT32_C(362880)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i64", UINT32_C(13))->to_ui64() == UINT32_C(55)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i64", UINT32_C(20))->to_ui64() == UINT32_C(9)));
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-i64", UINT32_C(11)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-i64", UINT32_C(22)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i32", UINT32_C(4))->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i32", UINT32_C(23))->to_ui32() == UINT32_C(362880)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i32", UINT32_C(26))->to_ui32() == UINT32_C(55)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "dispatch-structural-i32", UINT32_C(19))->to_ui32() == UINT32_C(9)));
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-i32", UINT32_C(9)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-i32", UINT32_C(21)), std::exception);
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "dispatch-structural-f32", UINT32_C(6))->to_f32()) == UINT32_C(1091567616)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "dispatch-structural-f32", UINT32_C(24))->to_f32()) == UINT32_C(1219571712)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "dispatch-structural-f32", UINT32_C(27))->to_f32()) == UINT32_C(1113325568)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "dispatch-structural-f32", UINT32_C(21))->to_f32()) == UINT32_C(1091567616)));
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-f32", UINT32_C(8)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-f32", UINT32_C(19)), std::exception);
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "dispatch-structural-f64", UINT32_C(7))->to_f64()) == UINT64_C(4621256167635550208)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "dispatch-structural-f64", UINT32_C(25))->to_f64()) == UINT64_C(4689977843394805760)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "dispatch-structural-f64", UINT32_C(28))->to_f64()) == UINT64_C(4632937379169042432)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "dispatch-structural-f64", UINT32_C(22))->to_f64()) == UINT64_C(4621256167635550208)));
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-f64", UINT32_C(10)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "dispatch-structural-f64", UINT32_C(18)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i64", UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i64", UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i64", UINT64_C(5))->to_ui64() == UINT32_C(120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i64", UINT64_C(25))->to_ui64() == UINT32_C(7034535277573963776)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i32", UINT32_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i32", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i32", UINT32_C(5))->to_ui32() == UINT32_C(120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fac-i32", UINT32_C(10))->to_ui32() == UINT32_C(3628800)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fac-f32", bit_cast<float>(UINT32_C(0)))->to_f32()) == UINT32_C(1065353216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fac-f32", bit_cast<float>(UINT32_C(1065353216)))->to_f32()) == UINT32_C(1065353216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fac-f32", bit_cast<float>(UINT32_C(1084227584)))->to_f32()) == UINT32_C(1123024896)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fac-f32", bit_cast<float>(UINT32_C(1092616192)))->to_f32()) == UINT32_C(1247640576)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fac-f64", bit_cast<double>(UINT64_C(0)))->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fac-f64", bit_cast<double>(UINT64_C(4607182418800017408)))->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fac-f64", bit_cast<double>(UINT64_C(4617315517961601024)))->to_f64()) == UINT64_C(4638144666238189568)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fac-f64", bit_cast<double>(UINT64_C(4621819117588971520)))->to_f64()) == UINT64_C(4705047200009289728)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i64", UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i64", UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i64", UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i64", UINT64_C(5))->to_ui64() == UINT32_C(8)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i64", UINT64_C(20))->to_ui64() == UINT32_C(10946)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i32", UINT32_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i32", UINT32_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i32", UINT32_C(2))->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i32", UINT32_C(5))->to_ui32() == UINT32_C(8)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "fib-i32", UINT32_C(20))->to_ui32() == UINT32_C(10946)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fib-f32", bit_cast<float>(UINT32_C(0)))->to_f32()) == UINT32_C(1065353216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fib-f32", bit_cast<float>(UINT32_C(1065353216)))->to_f32()) == UINT32_C(1065353216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fib-f32", bit_cast<float>(UINT32_C(1073741824)))->to_f32()) == UINT32_C(1073741824)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fib-f32", bit_cast<float>(UINT32_C(1084227584)))->to_f32()) == UINT32_C(1090519040)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "fib-f32", bit_cast<float>(UINT32_C(1101004800)))->to_f32()) == UINT32_C(1177225216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fib-f64", bit_cast<double>(UINT64_C(0)))->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fib-f64", bit_cast<double>(UINT64_C(4607182418800017408)))->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fib-f64", bit_cast<double>(UINT64_C(4611686018427387904)))->to_f64()) == UINT64_C(4611686018427387904)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fib-f64", bit_cast<double>(UINT64_C(4617315517961601024)))->to_f64()) == UINT64_C(4620693217682128896)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "fib-f64", bit_cast<double>(UINT64_C(4626322717216342016)))->to_f64()) == UINT64_C(4667243241467281408)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT32_C(0))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT32_C(1))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT32_C(100))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "even", UINT32_C(77))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT32_C(0))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT32_C(1))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT32_C(200))->to_ui32() == UINT32_C(99)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "odd", UINT32_C(77))->to_ui32() == UINT32_C(44)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first")->to_ui32() == UINT32_C(306)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-mid")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-condition")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-first")->to_ui64() == UINT32_C(356)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-br_table-first")->to_f32()) == UINT32_C(1165172736)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-last")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-first")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-last")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-memory.grow-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-return-value")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-drop-operand")));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-br-value")->to_f32()) == UINT32_C(1065353216)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "as-local.set-value")->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "as-local.tee-value")->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "as-global.set-value")->to_f64()) == UINT64_C(4607182418800017408)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-load-operand")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "as-unary-operand")->to_f32()) == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-left")->to_ui32() == UINT32_C(11)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-right")->to_ui32() == UINT32_C(9)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-test-operand")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-left")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-right")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-convert-operand")->to_ui64() == UINT32_C(1)));
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_12_wasm>", "[call_indirect_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.12.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_13_wasm>", "[call_indirect_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.13.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_14_wasm>", "[call_indirect_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_15_wasm>", "[call_indirect_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_16_wasm>", "[call_indirect_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_17_wasm>", "[call_indirect_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_18_wasm>", "[call_indirect_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_19_wasm>", "[call_indirect_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.19.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_20_wasm>", "[call_indirect_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.20.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_21_wasm>", "[call_indirect_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.21.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_22_wasm>", "[call_indirect_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.22.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_23_wasm>", "[call_indirect_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.23.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_24_wasm>", "[call_indirect_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.24.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_25_wasm>", "[call_indirect_25_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.25.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_26_wasm>", "[call_indirect_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.26.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_27_wasm>", "[call_indirect_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.27.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_28_wasm>", "[call_indirect_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.28.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_29_wasm>", "[call_indirect_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.29.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_30_wasm>", "[call_indirect_30_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.30.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_31_wasm>", "[call_indirect_31_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.31.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_32_wasm>", "[call_indirect_32_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.32.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <call_indirect_33_wasm>", "[call_indirect_33_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "call_indirect.33.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
