#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_float_literals_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <float_literals_0_wasm>", "[float_literals_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "float_literals.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.nan")->to_ui32() == UINT32_C(2143289344)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.positive_nan")->to_ui32() == UINT32_C(2143289344)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.negative_nan")->to_ui32() == UINT32_C(4290772992)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.plain_nan")->to_ui32() == UINT32_C(2143289344)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.informally_known_as_plain_snan")->to_ui32() == UINT32_C(2141192192)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.all_ones_nan")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.misc_nan")->to_ui32() == UINT32_C(2139169605)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.misc_positive_nan")->to_ui32() == UINT32_C(2142257232)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.misc_negative_nan")->to_ui32() == UINT32_C(4289379550)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.infinity")->to_ui32() == UINT32_C(2139095040)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.positive_infinity")->to_ui32() == UINT32_C(2139095040)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.negative_infinity")->to_ui32() == UINT32_C(4286578688)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.zero")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.positive_zero")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.negative_zero")->to_ui32() == UINT32_C(2147483648)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.misc")->to_ui32() == UINT32_C(1086918619)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.min_positive")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.min_normal")->to_ui32() == UINT32_C(8388608)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.max_subnormal")->to_ui32() == UINT32_C(8388607)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.max_finite")->to_ui32() == UINT32_C(2139095039)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32.trailing_dot")->to_ui32() == UINT32_C(1149239296)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.zero")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.positive_zero")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.negative_zero")->to_ui32() == UINT32_C(2147483648)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.misc")->to_ui32() == UINT32_C(1086918619)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.min_positive")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.min_normal")->to_ui32() == UINT32_C(8388608)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.max_subnormal")->to_ui32() == UINT32_C(8388607)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.max_finite")->to_ui32() == UINT32_C(2139095039)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.trailing_dot")->to_ui32() == UINT32_C(1343554297)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f32_dec.root_beer_float")->to_ui32() == UINT32_C(1065353217)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.nan")->to_ui64() == UINT32_C(9221120237041090560)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.positive_nan")->to_ui64() == UINT32_C(9221120237041090560)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.negative_nan")->to_ui64() == UINT32_C(18444492273895866368)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.plain_nan")->to_ui64() == UINT32_C(9221120237041090560)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.informally_known_as_plain_snan")->to_ui64() == UINT32_C(9219994337134247936)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.all_ones_nan")->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.misc_nan")->to_ui64() == UINT32_C(9218888453225749180)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.misc_positive_nan")->to_ui64() == UINT32_C(9219717281780008969)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.misc_negative_nan")->to_ui64() == UINT32_C(18442992325002076997)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.infinity")->to_ui64() == UINT32_C(9218868437227405312)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.positive_infinity")->to_ui64() == UINT32_C(9218868437227405312)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.negative_infinity")->to_ui64() == UINT32_C(18442240474082181120)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.zero")->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.positive_zero")->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.negative_zero")->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.misc")->to_ui64() == UINT32_C(4618760256179416344)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.min_positive")->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.min_normal")->to_ui64() == UINT32_C(4503599627370496)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.max_subnormal")->to_ui64() == UINT32_C(4503599627370495)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.max_finite")->to_ui64() == UINT32_C(9218868437227405311)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64.trailing_dot")->to_ui64() == UINT32_C(5057542381537067008)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.zero")->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.positive_zero")->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.negative_zero")->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.misc")->to_ui64() == UINT32_C(4618760256179416344)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.min_positive")->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.min_normal")->to_ui64() == UINT32_C(4503599627370496)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.max_subnormal")->to_ui64() == UINT32_C(4503599627370495)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.max_finite")->to_ui64() == UINT32_C(9218868437227405311)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.trailing_dot")->to_ui64() == UINT32_C(6103021453049119613)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "f64_dec.root_beer_float")->to_ui64() == UINT32_C(4607182419335945764)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-dec-sep1")->to_f32()) == UINT32_C(1232348160)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-dec-sep2")->to_f32()) == UINT32_C(1148846080)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-dec-sep3")->to_f32()) == UINT32_C(1148897552)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-dec-sep4")->to_f32()) == UINT32_C(1482758550)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-dec-sep5")->to_f32()) == UINT32_C(1847438964)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-hex-sep1")->to_f32()) == UINT32_C(1294004234)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-hex-sep2")->to_f32()) == UINT32_C(1205143424)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-hex-sep3")->to_f32()) == UINT32_C(1193345009)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-hex-sep4")->to_f32()) == UINT32_C(1240465408)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "f32-hex-sep5")->to_f32()) == UINT32_C(1437319208)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-dec-sep1")->to_f64()) == UINT64_C(4696837146684686336)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-dec-sep2")->to_f64()) == UINT64_C(4652007308841189376)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-dec-sep3")->to_f64()) == UINT64_C(4652034942576659200)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-dec-sep4")->to_f64()) == UINT64_C(2796837019126844485)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-dec-sep5")->to_f64()) == UINT64_C(5027061507362119324)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-hex-sep1")->to_f64()) == UINT64_C(4838519794133185330)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-hex-sep2")->to_f64()) == UINT64_C(4682231715257647104)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-hex-sep3")->to_f64()) == UINT64_C(4675897489574114112)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-hex-sep4")->to_f64()) == UINT64_C(4701195061021376512)));
   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "f64-hex-sep5")->to_f64()) == UINT64_C(4806880140420149248)));
}

BACKEND_TEST_CASE( "Testing wasm <float_literals_1_wasm>", "[float_literals_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "float_literals.1.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bit_cast<uint64_t>(bkend.call_with_return("env", "4294967249")->to_f64()) == UINT64_C(4751297606777307136)));
}
