#include "test_prelude.hpp"
import forge.vm.wasm.backend;
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_i64_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <i64_0_wasm>", "[i64_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(9223372036854775807), UINT64_C(1))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "add", UINT64_C(1073741823), UINT64_C(1))->to_ui64() == UINT32_C(1073741824)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(9223372036854775807), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(9223372036854775808), UINT64_C(1))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "sub", UINT64_C(1073741823), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(1073741824)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(1152921504606846976), UINT64_C(4096))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(9223372036854775807), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775809)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(81985529216486895), UINT64_C(18364758544493064720))->to_ui64() == UINT32_C(2465395958572223728)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "mul", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(1)));
   BOOST_CHECK_THROW(bkend("env", "div_s", UINT64_C(1), UINT64_C(0)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "div_s", UINT64_C(0), UINT64_C(0)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "div_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(0), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(9223372036854775808), UINT64_C(2))->to_ui64() == UINT32_C(13835058055282163712)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(9223372036854775809), UINT64_C(1000))->to_ui64() == UINT32_C(18437520701672696841)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(5), UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(18446744073709551611), UINT64_C(2))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(5), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(18446744073709551611), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(7), UINT64_C(3))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(18446744073709551609), UINT64_C(3))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(7), UINT64_C(18446744073709551613))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(18446744073709551609), UINT64_C(18446744073709551613))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(11), UINT64_C(5))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_s", UINT64_C(17), UINT64_C(7))->to_ui64() == UINT32_C(2)));
   BOOST_CHECK_THROW(bkend("env", "div_u", UINT64_C(1), UINT64_C(0)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "div_u", UINT64_C(0), UINT64_C(0)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(9223372036854775808), UINT64_C(2))->to_ui64() == UINT32_C(4611686018427387904)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(10371807465568210928), UINT64_C(4294967297))->to_ui64() == UINT32_C(2414874607)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(9223372036854775809), UINT64_C(1000))->to_ui64() == UINT32_C(9223372036854775)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(5), UINT64_C(2))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(18446744073709551611), UINT64_C(2))->to_ui64() == UINT32_C(9223372036854775805)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(5), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(18446744073709551611), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(7), UINT64_C(3))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(11), UINT64_C(5))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "div_u", UINT64_C(17), UINT64_C(7))->to_ui64() == UINT32_C(2)));
   BOOST_CHECK_THROW(bkend("env", "rem_s", UINT64_C(1), UINT64_C(0)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "rem_s", UINT64_C(0), UINT64_C(0)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(9223372036854775807), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(0), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(9223372036854775808), UINT64_C(2))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(9223372036854775809), UINT64_C(1000))->to_ui64() == UINT32_C(18446744073709550809)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(5), UINT64_C(2))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(18446744073709551611), UINT64_C(2))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(5), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(18446744073709551611), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(7), UINT64_C(3))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(18446744073709551609), UINT64_C(3))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(7), UINT64_C(18446744073709551613))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(18446744073709551609), UINT64_C(18446744073709551613))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(11), UINT64_C(5))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_s", UINT64_C(17), UINT64_C(7))->to_ui64() == UINT32_C(3)));
   BOOST_CHECK_THROW(bkend("env", "rem_u", UINT64_C(1), UINT64_C(0)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "rem_u", UINT64_C(0), UINT64_C(0)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(9223372036854775808), UINT64_C(2))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(10371807465568210928), UINT64_C(4294967297))->to_ui64() == UINT32_C(2147483649)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(9223372036854775809), UINT64_C(1000))->to_ui64() == UINT32_C(809)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(5), UINT64_C(2))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(18446744073709551611), UINT64_C(2))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(5), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(18446744073709551611), UINT64_C(18446744073709551614))->to_ui64() == UINT32_C(18446744073709551611)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(7), UINT64_C(3))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(11), UINT64_C(5))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rem_u", UINT64_C(17), UINT64_C(7))->to_ui64() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(0), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(9223372036854775807), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(4042326015), UINT64_C(4294963440))->to_ui64() == UINT32_C(4042322160)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "and", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(0), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(4042326015), UINT64_C(4294963440))->to_ui64() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "or", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(0), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(0), UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(18446744073709551615), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(4042326015), UINT64_C(4294963440))->to_ui64() == UINT32_C(252645135)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "xor", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(9223372036854775807), UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(9223372036854775808), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(4611686018427387904), UINT64_C(1))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(63))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(64))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(65))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shl", UINT64_C(1), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(9223372036854775807), UINT64_C(1))->to_ui64() == UINT32_C(4611686018427387903)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(9223372036854775808), UINT64_C(1))->to_ui64() == UINT32_C(13835058055282163712)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(4611686018427387904), UINT64_C(1))->to_ui64() == UINT32_C(2305843009213693952)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(64))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(65))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(1), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(9223372036854775808), UINT64_C(63))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(64))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(65))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(9223372036854775807), UINT64_C(1))->to_ui64() == UINT32_C(4611686018427387903)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(9223372036854775808), UINT64_C(1))->to_ui64() == UINT32_C(4611686018427387904)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(4611686018427387904), UINT64_C(1))->to_ui64() == UINT32_C(2305843009213693952)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(64))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(65))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(1), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(9223372036854775808), UINT64_C(63))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(64))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(65))->to_ui64() == UINT32_C(9223372036854775807)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "shr_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(1), UINT64_C(64))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12379718583323101902), UINT64_C(1))->to_ui64() == UINT32_C(6312693092936652189)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(18302628889324683264), UINT64_C(4))->to_ui64() == UINT32_C(16140901123551657999)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12379570969274382345), UINT64_C(53))->to_ui64() == UINT32_C(87109505680009935)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12380715672649826460), UINT64_C(63))->to_ui64() == UINT32_C(6190357836324913230)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12379570969274382345), UINT64_C(245))->to_ui64() == UINT32_C(87109505680009935)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12379676934707509257), UINT64_C(18446744073709551597))->to_ui64() == UINT32_C(14916262237559758314)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(12380715672649826460), UINT64_C(9223372036854775871))->to_ui64() == UINT32_C(6190357836324913230)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(1), UINT64_C(63))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotl", UINT64_C(9223372036854775808), UINT64_C(1))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(1), UINT64_C(1))->to_ui64() == UINT32_C(9223372036854775808)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(1), UINT64_C(0))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(1), UINT64_C(64))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12379718583323101902), UINT64_C(1))->to_ui64() == UINT32_C(6189859291661550951)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(18302628889324683264), UINT64_C(4))->to_ui64() == UINT32_C(1143914305582792704)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12379570969274382345), UINT64_C(53))->to_ui64() == UINT32_C(7534987797011123550)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12380715672649826460), UINT64_C(63))->to_ui64() == UINT32_C(6314687271590101305)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12379570969274382345), UINT64_C(245))->to_ui64() == UINT32_C(7534987797011123550)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12379676934707509257), UINT64_C(18446744073709551597))->to_ui64() == UINT32_C(10711665151168044651)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(12380715672649826460), UINT64_C(9223372036854775871))->to_ui64() == UINT32_C(6314687271590101305)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(1), UINT64_C(63))->to_ui64() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "rotr", UINT64_C(9223372036854775808), UINT64_C(63))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(0))->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(32768))->to_ui64() == UINT32_C(48)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(255))->to_ui64() == UINT32_C(56)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(1))->to_ui64() == UINT32_C(63)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(2))->to_ui64() == UINT32_C(62)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "clz", UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(0))->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(32768))->to_ui64() == UINT32_C(15)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(65536))->to_ui64() == UINT32_C(16)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(9223372036854775808))->to_ui64() == UINT32_C(63)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ctz", UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(18446744073709551615))->to_ui64() == UINT32_C(64)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(32768))->to_ui64() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(9223512776490647552))->to_ui64() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(9223372036854775807))->to_ui64() == UINT32_C(63)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(12297829381041378645))->to_ui64() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(11068046444512062122))->to_ui64() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "popcnt", UINT64_C(16045690984833335023))->to_ui64() == UINT32_C(48)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eqz", UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eqz", UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eqz", UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eqz", UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eqz", UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "eq", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ne", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "lt_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "le_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "gt_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_s", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(0), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(1), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(18446744073709551615), UINT64_C(1))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(18446744073709551615), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(1), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(0), UINT64_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775808), UINT64_C(0))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(0), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775808), UINT64_C(18446744073709551615))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(18446744073709551615), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775808), UINT64_C(9223372036854775807))->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "ge_u", UINT64_C(9223372036854775807), UINT64_C(9223372036854775808))->to_ui32() == UINT32_C(0)));
}

BACKEND_TEST_CASE( "Testing wasm <i64_1_wasm>", "[i64_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_10_wasm>", "[i64_10_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.10.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_11_wasm>", "[i64_11_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.11.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_12_wasm>", "[i64_12_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.12.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_13_wasm>", "[i64_13_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.13.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_14_wasm>", "[i64_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_15_wasm>", "[i64_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_16_wasm>", "[i64_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_17_wasm>", "[i64_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_18_wasm>", "[i64_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_19_wasm>", "[i64_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.19.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_2_wasm>", "[i64_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.2.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_20_wasm>", "[i64_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.20.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_21_wasm>", "[i64_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.21.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_22_wasm>", "[i64_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.22.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_23_wasm>", "[i64_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.23.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_24_wasm>", "[i64_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.24.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_25_wasm>", "[i64_25_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.25.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_26_wasm>", "[i64_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.26.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_27_wasm>", "[i64_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.27.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_28_wasm>", "[i64_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.28.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_29_wasm>", "[i64_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.29.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_3_wasm>", "[i64_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.3.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_4_wasm>", "[i64_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_5_wasm>", "[i64_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.5.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_6_wasm>", "[i64_6_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.6.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_7_wasm>", "[i64_7_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.7.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_8_wasm>", "[i64_8_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.8.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <i64_9_wasm>", "[i64_9_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "i64.9.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
