#include "test_prelude.hpp"
import forge.vm.wasm.interpret.allocator;
import forge.vm.wasm.interpret.stack_elem;
import forge.vm.wasm.interpret.utils;
import forge.vm.wasm.interpret.backend;
#define FORGE_VM_WASM_INTERPRET_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_INTERPRET_TEST_FILE spec_load_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm::interpret;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <load_0_wasm>", "[load_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br-value")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_if-cond")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_if-value-cond")->to_ui32() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-br_table-index")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-br_table-value-index")->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-return-value")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-cond")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-then")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-else")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-first", UINT32_C(0), UINT32_C(1))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-second", UINT32_C(0), UINT32_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-select-cond")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-first")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-mid")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call-last")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-first")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-mid")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-last")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-call_indirect-index")->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-local.set-value")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-local.tee-value")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-global.set-value")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-load-address")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loadN-address")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-address")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-store-value")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-storeN-address")));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "as-storeN-value")));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-unary-operand")->to_ui32() == UINT32_C(32)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-left")->to_ui32() == UINT32_C(10)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-binary-right")->to_ui32() == UINT32_C(10)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-test-operand")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-left")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-compare-right")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-memory.grow-size")->to_ui32() == UINT32_C(1)));
}

BACKEND_TEST_CASE( "Testing wasm <load_14_wasm>", "[load_14_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.14.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_15_wasm>", "[load_15_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.15.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_16_wasm>", "[load_16_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.16.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_17_wasm>", "[load_17_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.17.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_18_wasm>", "[load_18_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.18.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_19_wasm>", "[load_19_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.19.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_20_wasm>", "[load_20_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.20.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_21_wasm>", "[load_21_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.21.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_22_wasm>", "[load_22_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.22.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_23_wasm>", "[load_23_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.23.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_24_wasm>", "[load_24_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.24.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_25_wasm>", "[load_25_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.25.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_26_wasm>", "[load_26_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.26.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_27_wasm>", "[load_27_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.27.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_28_wasm>", "[load_28_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.28.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_29_wasm>", "[load_29_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.29.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_30_wasm>", "[load_30_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.30.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_31_wasm>", "[load_31_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.31.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_32_wasm>", "[load_32_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.32.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_33_wasm>", "[load_33_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.33.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_34_wasm>", "[load_34_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.34.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_35_wasm>", "[load_35_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.35.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_36_wasm>", "[load_36_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.36.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_37_wasm>", "[load_37_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.37.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_38_wasm>", "[load_38_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.38.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_39_wasm>", "[load_39_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.39.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_40_wasm>", "[load_40_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.40.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_41_wasm>", "[load_41_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.41.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_42_wasm>", "[load_42_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.42.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_43_wasm>", "[load_43_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.43.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_44_wasm>", "[load_44_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.44.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_45_wasm>", "[load_45_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.45.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_46_wasm>", "[load_46_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.46.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_47_wasm>", "[load_47_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.47.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_48_wasm>", "[load_48_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.48.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_49_wasm>", "[load_49_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.49.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_50_wasm>", "[load_50_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.50.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_51_wasm>", "[load_51_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.51.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_52_wasm>", "[load_52_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.52.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_53_wasm>", "[load_53_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.53.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_54_wasm>", "[load_54_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.54.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_55_wasm>", "[load_55_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.55.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_56_wasm>", "[load_56_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.56.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_57_wasm>", "[load_57_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.57.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_58_wasm>", "[load_58_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.58.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <load_59_wasm>", "[load_59_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "load.59.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
