#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_memory_redundancy_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <memory_redundancy_0_wasm>", "[memory_redundancy_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_redundancy.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "test_store_to_load")->to_ui32() == UINT32_C(128)));
bkend("env", "zero_everything");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "test_redundant_load")->to_ui32() == UINT32_C(128)));
bkend("env", "zero_everything");
   BOOST_TEST(static_cast<bool>(bit_cast<uint32_t>(bkend.call_with_return("env", "test_dead_store")->to_f32()) == UINT32_C(35)));
bkend("env", "zero_everything");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "malloc_aliasing")->to_ui32() == UINT32_C(43)));
}
