#include "test_prelude.hpp"
import forge.vm.wasm.interpret.allocator;
import forge.vm.wasm.interpret.stack_elem;
import forge.vm.wasm.interpret.utils;
import forge.vm.wasm.interpret.backend;
#define FORGE_VM_WASM_INTERPRET_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_INTERPRET_TEST_FILE spec_memory_size_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm::interpret;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <memory_size_0_wasm>", "[memory_size_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(4))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(5)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(5)));
}

BACKEND_TEST_CASE( "Testing wasm <memory_size_1_wasm>", "[memory_size_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.1.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(2)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(4))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(6)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(6)));
}

BACKEND_TEST_CASE( "Testing wasm <memory_size_2_wasm>", "[memory_size_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.2.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(3))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(4))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(1)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(2)));
}

BACKEND_TEST_CASE( "Testing wasm <memory_size_3_wasm>", "[memory_size_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.3.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(3)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(3))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(0))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(2))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(7)));
   BOOST_TEST(static_cast<bool>(!bkend.call_with_return("env", "grow", UINT32_C(1))));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "size")->to_ui32() == UINT32_C(8)));
}

BACKEND_TEST_CASE( "Testing wasm <memory_size_4_wasm>", "[memory_size_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <memory_size_5_wasm>", "[memory_size_5_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "memory_size.5.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
