#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_start_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <start_0_wasm>", "[start_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "start.0.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <start_1_wasm>", "[start_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "start.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <start_2_wasm>", "[start_2_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "start.2.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <start_3_wasm>", "[start_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "start.3.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(68)));
bkend("env", "inc");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(69)));
bkend("env", "inc");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(70)));
}

BACKEND_TEST_CASE( "Testing wasm <start_4_wasm>", "[start_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "start.4.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(68)));
bkend("env", "inc");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(69)));
bkend("env", "inc");
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "get")->to_ui32() == UINT32_C(70)));
}
