#include "test_prelude.hpp"
import forge.vm.wasm.backend;
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_switch_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <switch_0_wasm>", "[switch_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "switch.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(0))->to_ui32() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(1))->to_ui32() == UINT32_C(4294967295)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(2))->to_ui32() == UINT32_C(4294967294)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(3))->to_ui32() == UINT32_C(4294967293)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(4))->to_ui32() == UINT32_C(100)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(5))->to_ui32() == UINT32_C(101)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(6))->to_ui32() == UINT32_C(102)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(7))->to_ui32() == UINT32_C(100)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "stmt", UINT32_C(4294967286))->to_ui32() == UINT32_C(102)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(0))->to_ui64() == UINT32_C(0)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(1))->to_ui64() == UINT32_C(18446744073709551615)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(2))->to_ui64() == UINT32_C(18446744073709551614)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(3))->to_ui64() == UINT32_C(18446744073709551613)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(6))->to_ui64() == UINT32_C(101)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(7))->to_ui64() == UINT32_C(18446744073709551611)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "expr", UINT64_C(18446744073709551606))->to_ui64() == UINT32_C(100)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(0))->to_ui32() == UINT32_C(110)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(1))->to_ui32() == UINT32_C(12)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(2))->to_ui32() == UINT32_C(4)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(3))->to_ui32() == UINT32_C(1116)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(4))->to_ui32() == UINT32_C(118)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(5))->to_ui32() == UINT32_C(20)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(6))->to_ui32() == UINT32_C(12)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(7))->to_ui32() == UINT32_C(1124)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "arg", UINT32_C(8))->to_ui32() == UINT32_C(126)));
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "corner")->to_ui32() == UINT32_C(1)));
}

BACKEND_TEST_CASE( "Testing wasm <switch_1_wasm>", "[switch_1_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "switch.1.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
