#include "test_prelude.hpp"
import forge.vm.wasm.interpret.allocator;
import forge.vm.wasm.interpret.stack_elem;
import forge.vm.wasm.interpret.utils;
import forge.vm.wasm.interpret.backend;
#define FORGE_VM_WASM_INTERPRET_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_INTERPRET_TEST_FILE spec_type_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm::interpret;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <type_0_wasm>", "[type_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "type.0.wasm");
   backend_t bkend( code, &wa );

}

BACKEND_TEST_CASE( "Testing wasm <type_3_wasm>", "[type_3_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "type.3.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}

BACKEND_TEST_CASE( "Testing wasm <type_4_wasm>", "[type_4_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "type.4.wasm");
   BOOST_CHECK_THROW(backend_t(code, nullptr), std::exception);
}
