#include "test_prelude.hpp"
import forge.vm.wasm.allocator;
import forge.vm.wasm.stack_elem;
import forge.vm.wasm.utils;
import forge.vm.wasm.backend;
#define FORGE_VM_WASM_TEST_USES_BACKEND
#include "test_support.hpp"

#define FORGE_VM_WASM_TEST_FILE spec_unreachable_tests

// Generated by spec_test_generator.  DO NOT MODIFY THIS FILE.

#include <algorithm>
#include <vector>
#include <iostream>
#include <iterator>
#include <cmath>
#include <cstdlib>



using namespace forge::vm::wasm;
extern wasm_allocator wa;

BACKEND_TEST_CASE( "Testing wasm <unreachable_0_wasm>", "[unreachable_0_wasm_tests]" ) {
   using backend_t = backend<standalone_function_t, TestType>;
   auto code = read_wasm( std::string(wasm_directory) + "unreachable.0.wasm");
   backend_t bkend( code, &wa );

   BOOST_CHECK_THROW(bkend("env", "type-i32"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "type-i64"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "type-f32"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "type-f64"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-func-first"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-func-mid"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-func-last"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-func-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-block-first"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-block-mid"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-block-last"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-block-value"), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-block-broke")->to_ui32() == UINT32_C(1)));
   BOOST_CHECK_THROW(bkend("env", "as-loop-first"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-loop-mid"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-loop-last"), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-loop-broke")->to_ui32() == UINT32_C(1)));
   BOOST_CHECK_THROW(bkend("env", "as-br-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_if-cond"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_if-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_if-value-cond"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_table-index"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_table-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_table-value-2"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_table-value-index"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-br_table-value-and-index"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-return-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-if-cond"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-if-then", UINT32_C(1), UINT32_C(6)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-then", UINT32_C(0), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_CHECK_THROW(bkend("env", "as-if-else", UINT32_C(0), UINT32_C(6)), std::exception);
   BOOST_TEST(static_cast<bool>(bkend.call_with_return("env", "as-if-else", UINT32_C(1), UINT32_C(6))->to_ui32() == UINT32_C(6)));
   BOOST_CHECK_THROW(bkend("env", "as-select-first", UINT32_C(0), UINT32_C(6)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-select-first", UINT32_C(1), UINT32_C(6)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-select-second", UINT32_C(0), UINT32_C(6)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-select-second", UINT32_C(1), UINT32_C(6)), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-select-cond"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call-first"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call-mid"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call-last"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call_indirect-func"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call_indirect-first"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call_indirect-mid"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-call_indirect-last"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-local.set-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-local.tee-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-global.set-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-load-address"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-loadN-address"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-store-address"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-store-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-storeN-address"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-storeN-value"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-unary-operand"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-binary-left"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-binary-right"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-test-operand"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-compare-left"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-compare-right"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-convert-operand"), std::exception);
   BOOST_CHECK_THROW(bkend("env", "as-memory.grow-size"), std::exception);
}
