module;

#include <forge/vm/wasm/opcode_macros.hpp>
#include <cstdint>
#include <map>
#include <string>

export module forge.vm.wasm.opcodes;

export import forge.vm.wasm.variant;

export namespace forge::vm::wasm {
enum opcodes {
   FORGE_VM_WASM_CONTROL_FLOW_OPS(FORGE_VM_WASM_CREATE_ENUM) FORGE_VM_WASM_BR_TABLE_OP(FORGE_VM_WASM_CREATE_ENUM)
       FORGE_VM_WASM_RETURN_OP(FORGE_VM_WASM_CREATE_ENUM) FORGE_VM_WASM_CALL_OPS(FORGE_VM_WASM_CREATE_ENUM)
           FORGE_VM_WASM_CALL_IMM_OPS(FORGE_VM_WASM_CREATE_ENUM) FORGE_VM_WASM_PARAMETRIC_OPS(FORGE_VM_WASM_CREATE_ENUM)
               FORGE_VM_WASM_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_CREATE_ENUM)
                   FORGE_VM_WASM_MEMORY_OPS(FORGE_VM_WASM_CREATE_ENUM)
                       FORGE_VM_WASM_I32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_ENUM)
                           FORGE_VM_WASM_I64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_ENUM)
                               FORGE_VM_WASM_F32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                   FORGE_VM_WASM_F64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                       FORGE_VM_WASM_COMPARISON_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                           FORGE_VM_WASM_NUMERIC_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                               FORGE_VM_WASM_CONVERSION_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                                   FORGE_VM_WASM_EXIT_OP(FORGE_VM_WASM_CREATE_ENUM)
                                                       FORGE_VM_WASM_EMPTY_OPS(FORGE_VM_WASM_CREATE_ENUM)
                                                           FORGE_VM_WASM_ERROR_OPS(FORGE_VM_WASM_CREATE_ENUM)
};

struct opcode_utils {
   std::map<uint16_t, std::string> opcode_map{
       FORGE_VM_WASM_CONTROL_FLOW_OPS(FORGE_VM_WASM_CREATE_MAP) FORGE_VM_WASM_BR_TABLE_OP(FORGE_VM_WASM_CREATE_MAP)
           FORGE_VM_WASM_RETURN_OP(FORGE_VM_WASM_CREATE_MAP) FORGE_VM_WASM_CALL_OPS(FORGE_VM_WASM_CREATE_MAP)
               FORGE_VM_WASM_CALL_IMM_OPS(FORGE_VM_WASM_CREATE_MAP)
                   FORGE_VM_WASM_PARAMETRIC_OPS(FORGE_VM_WASM_CREATE_MAP)
                       FORGE_VM_WASM_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_CREATE_MAP)
                           FORGE_VM_WASM_MEMORY_OPS(FORGE_VM_WASM_CREATE_MAP)
                               FORGE_VM_WASM_I32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_MAP)
                                   FORGE_VM_WASM_I64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_MAP)
                                       FORGE_VM_WASM_F32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_MAP)
                                           FORGE_VM_WASM_F64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_MAP)
                                               FORGE_VM_WASM_COMPARISON_OPS(FORGE_VM_WASM_CREATE_MAP)
                                                   FORGE_VM_WASM_NUMERIC_OPS(FORGE_VM_WASM_CREATE_MAP)
                                                       FORGE_VM_WASM_CONVERSION_OPS(FORGE_VM_WASM_CREATE_MAP)
                                                           FORGE_VM_WASM_EXIT_OP(FORGE_VM_WASM_CREATE_MAP)
                                                               FORGE_VM_WASM_EMPTY_OPS(FORGE_VM_WASM_CREATE_MAP)
                                                                   FORGE_VM_WASM_ERROR_OPS(FORGE_VM_WASM_CREATE_MAP)};
};

enum imm_types {
   none,
   block_imm,
   varuint32_imm,
   br_table_imm,
};

FORGE_VM_WASM_CONTROL_FLOW_OPS(FORGE_VM_WASM_CREATE_CONTROL_FLOW_TYPES)
FORGE_VM_WASM_BR_TABLE_OP(FORGE_VM_WASM_CREATE_BR_TABLE_TYPE)
FORGE_VM_WASM_RETURN_OP(FORGE_VM_WASM_CREATE_CONTROL_FLOW_TYPES)
FORGE_VM_WASM_CALL_OPS(FORGE_VM_WASM_CREATE_CALL_TYPES)
FORGE_VM_WASM_CALL_IMM_OPS(FORGE_VM_WASM_CREATE_CALL_IMM_TYPES)
FORGE_VM_WASM_PARAMETRIC_OPS(FORGE_VM_WASM_CREATE_TYPES)
FORGE_VM_WASM_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_CREATE_VARIABLE_ACCESS_TYPES)
FORGE_VM_WASM_MEMORY_OPS(FORGE_VM_WASM_CREATE_MEMORY_TYPES)
FORGE_VM_WASM_I32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_I32_CONSTANT_TYPE)
FORGE_VM_WASM_I64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_I64_CONSTANT_TYPE)
FORGE_VM_WASM_F32_CONSTANT_OPS(FORGE_VM_WASM_CREATE_F32_CONSTANT_TYPE)
FORGE_VM_WASM_F64_CONSTANT_OPS(FORGE_VM_WASM_CREATE_F64_CONSTANT_TYPE)
FORGE_VM_WASM_COMPARISON_OPS(FORGE_VM_WASM_CREATE_TYPES)
FORGE_VM_WASM_NUMERIC_OPS(FORGE_VM_WASM_CREATE_TYPES)
FORGE_VM_WASM_CONVERSION_OPS(FORGE_VM_WASM_CREATE_TYPES)
FORGE_VM_WASM_EXIT_OP(FORGE_VM_WASM_CREATE_EXIT_TYPE)
FORGE_VM_WASM_EMPTY_OPS(FORGE_VM_WASM_CREATE_TYPES)
FORGE_VM_WASM_ERROR_OPS(FORGE_VM_WASM_CREATE_TYPES)

using opcode =
    variant<FORGE_VM_WASM_CONTROL_FLOW_OPS(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_BR_TABLE_OP(FORGE_VM_WASM_IDENTITY)
                FORGE_VM_WASM_RETURN_OP(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_CALL_OPS(FORGE_VM_WASM_IDENTITY)
                    FORGE_VM_WASM_CALL_IMM_OPS(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_PARAMETRIC_OPS(
                        FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_IDENTITY)
                        FORGE_VM_WASM_MEMORY_OPS(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_I32_CONSTANT_OPS(
                            FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_I64_CONSTANT_OPS(FORGE_VM_WASM_IDENTITY)
                            FORGE_VM_WASM_F32_CONSTANT_OPS(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_F64_CONSTANT_OPS(
                                FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_COMPARISON_OPS(FORGE_VM_WASM_IDENTITY)
                                FORGE_VM_WASM_NUMERIC_OPS(FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_CONVERSION_OPS(
                                    FORGE_VM_WASM_IDENTITY) FORGE_VM_WASM_EXIT_OP(FORGE_VM_WASM_IDENTITY)
                                    FORGE_VM_WASM_EMPTY_OPS(FORGE_VM_WASM_IDENTITY)
                                        FORGE_VM_WASM_ERROR_OPS(FORGE_VM_WASM_IDENTITY_END)>;
} // namespace forge::vm::wasm
