#!/usr/bin/env python3
import argparse
import hashlib
import json
import os
import stat
import struct
import subprocess
from dataclasses import dataclass
from pathlib import Path


WORKTREE_FINGERPRINT_FORMAT = b"forge-libp2p-interop-worktree-v1\0"


@dataclass(frozen=True)
class WorktreeIdentity:
    head: str
    fingerprint: str
    dirty: bool

    def as_json(self) -> dict:
        return {
            "head": self.head,
            "worktree_sha256": self.fingerprint,
            "dirty": self.dirty,
            "exact_identity": f"git:{self.head};worktree-sha256:{self.fingerprint}",
        }


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as value:
        while chunk := value.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def graph_hash(root: Path, paths: list[str]) -> str:
    digest = hashlib.sha256()
    for relative in paths:
        path = root / relative
        digest.update(relative.encode())
        digest.update(b"\0")
        with path.open("rb") as value:
            while chunk := value.read(1024 * 1024):
                digest.update(chunk)
        digest.update(b"\0")
    return digest.hexdigest()


def git_output(root: Path, *args: str) -> bytes:
    try:
        return subprocess.check_output(["git", "-C", str(root), *args])
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"Git command failed for {root}: {error}") from error


def worktree_identity(root: Path) -> WorktreeIdentity:
    root = root.resolve()
    head = git_output(root, "rev-parse", "HEAD").decode("ascii").strip()
    entries = git_output(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
    paths = sorted({value for value in entries.split(b"\0") if value})

    digest = hashlib.sha256()
    digest.update(WORKTREE_FINGERPRINT_FORMAT)
    digest.update(b"head\0")
    digest.update(head.encode("ascii"))
    digest.update(b"\0")
    for relative in paths:
        if relative.startswith(b"/") or b".." in relative.split(b"/"):
            raise RuntimeError(f"Git returned an unsafe worktree path: {relative!r}")
        path = root / os.fsdecode(relative)
        digest.update(b"path\0")
        digest.update(struct.pack(">Q", len(relative)))
        digest.update(relative)
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            digest.update(b"missing\0")
            continue
        if stat.S_ISLNK(metadata.st_mode):
            target = os.fsencode(os.readlink(path))
            digest.update(b"symlink\0")
            digest.update(struct.pack(">Q", len(target)))
            digest.update(target)
            continue
        if stat.S_ISREG(metadata.st_mode):
            digest.update(b"content\0")
            digest.update(struct.pack(">Q", metadata.st_size))
            read = 0
            with path.open("rb") as value:
                while chunk := value.read(1024 * 1024):
                    digest.update(chunk)
                    read += len(chunk)
            if read != metadata.st_size:
                raise RuntimeError(f"worktree file changed while fingerprinting: {path}")
            continue
        digest.update(b"other\0")
        digest.update(struct.pack(">I", stat.S_IFMT(metadata.st_mode)))

    dirty = bool(git_output(root, "status", "--porcelain=v1", "-z"))
    return WorktreeIdentity(head=head, fingerprint=digest.hexdigest(), dirty=dirty)


def write_if_changed(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == value:
        return
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(value)
    temporary.replace(path)


def cxx_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def emit_build_info(root: Path, output_header: Path, output_stamp: Path, compiler_path: str,
                    compiler_id: str, compiler_version: str) -> None:
    identity = worktree_identity(root)
    compiler = {
        "path": str(Path(compiler_path).resolve()),
        "id": compiler_id,
        "version": compiler_version,
    }
    header = (
        "// Generated by tests/libp2p_interop/provenance.py.\n"
        "#pragma once\n"
        f"#define FORGE_INTEROP_BUILD_FORGE_HEAD {cxx_string(identity.head)}\n"
        f"#define FORGE_INTEROP_BUILD_WORKTREE_SHA256 {cxx_string(identity.fingerprint)}\n"
        f"#define FORGE_INTEROP_BUILD_WORKTREE_DIRTY {1 if identity.dirty else 0}\n"
        f"#define FORGE_INTEROP_BUILD_COMPILER_PATH {cxx_string(compiler['path'])}\n"
        f"#define FORGE_INTEROP_BUILD_COMPILER_ID {cxx_string(compiler['id'])}\n"
        f"#define FORGE_INTEROP_BUILD_COMPILER_VERSION {cxx_string(compiler['version'])}\n"
    )
    stamp = json.dumps(
        {
            "schema_version": 1,
            "forge": identity.as_json(),
            "compiler": compiler,
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    write_if_changed(output_header, header)
    write_if_changed(output_stamp, stamp)


def main() -> int:
    parser = argparse.ArgumentParser()
    subcommands = parser.add_subparsers(dest="command", required=True)
    fingerprint = subcommands.add_parser("fingerprint")
    fingerprint.add_argument("--forge-root", required=True)
    build_info = subcommands.add_parser("emit-build-info")
    build_info.add_argument("--forge-root", required=True)
    build_info.add_argument("--output-header", required=True)
    build_info.add_argument("--output-stamp", required=True)
    build_info.add_argument("--compiler-path", required=True)
    build_info.add_argument("--compiler-id", required=True)
    build_info.add_argument("--compiler-version", required=True)
    args = parser.parse_args()

    if args.command == "fingerprint":
        print(json.dumps(worktree_identity(Path(args.forge_root)).as_json(), sort_keys=True))
        return 0
    emit_build_info(
        Path(args.forge_root),
        Path(args.output_header),
        Path(args.output_stamp),
        args.compiler_path,
        args.compiler_id,
        args.compiler_version,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
