add_library(
   forge_guest_contract STATIC
   action.cpp
   authorization.cpp
   bitset.cpp
   call.cpp
   compatibility_asset.cpp
   crypto.cpp
   crypto_bls_ext.cpp
   crypto_ext.cpp
   deferred_transaction.cpp
   dispatcher.cpp
   instant_finality.cpp
   intrinsics.cpp
   print.cpp
   privileged.cpp
   producer_schedule.cpp
   rope.cpp
   system.cpp
   transaction.cpp
)
target_sources(
   forge_guest_contract
   PUBLIC
      FILE_SET CXX_MODULES
      BASE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/include"
      FILES
         include/forge/contract/intrinsics.cppm
         include/forge/contract/contract.cppm
         include/forge/contract/datastream.cppm
         include/forge/contract/varint.cppm
         include/forge/contract/fixed_bytes.cppm
         include/forge/contract/binary_extension.cppm
         include/forge/contract/ignore.cppm
         include/forge/contract/hash_id.cppm
         include/forge/contract/action.cppm
         include/forge/contract/transaction.cppm
         include/forge/contract/deferred_transaction.cppm
         include/forge/contract/authorization.cppm
         include/forge/contract/bitset.cppm
         include/forge/contract/call.cppm
         include/forge/contract/crypto.cppm
         include/forge/contract/crypto_bls_ext.cppm
         include/forge/contract/crypto_ext.cppm
         include/forge/contract/instant_finality.cppm
         include/forge/contract/key.cppm
         include/forge/contract/powers.cppm
         include/forge/contract/system.cppm
         include/forge/contract/print.cppm
         include/forge/contract/privileged.cppm
         include/forge/contract/producer_schedule.cppm
         include/forge/contract/rope.cppm
         include/forge/contract/string.cppm
         include/forge/contract/dispatcher.cppm
         include/forge/contract/multi_index.cppm
         include/forge/contract/singleton.cppm
         include/forge/contract/compatibility_name.cppm
         include/forge/contract/compatibility_asset.cppm
)
target_include_directories(
   forge_guest_contract
   PUBLIC
      "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
)
target_link_libraries(forge_guest_contract PRIVATE Boost::headers)
target_link_libraries(
   forge_guest_contract
   PUBLIC
      forge_guest_runtime
      forge_guest_raw
      forge_guest_chain_protocol
      forge_guest_codec_base64
      forge_guest_codec_base58
      forge_guest_codec_hex
)
target_compile_features(forge_guest_contract PUBLIC cxx_std_23)
