module;

#include <forge/vm/wasm/interpret/opcode_macros.hpp>
#include <cstdint>
#include <map>
#include <string>

export module forge.vm.wasm.interpret.opcodes;

export import forge.vm.wasm.interpret.variant;

export namespace forge::vm::wasm::interpret {
enum opcodes {
   FORGE_VM_WASM_INTERPRET_CONTROL_FLOW_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM) FORGE_VM_WASM_INTERPRET_BR_TABLE_OP(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
       FORGE_VM_WASM_INTERPRET_RETURN_OP(FORGE_VM_WASM_INTERPRET_CREATE_ENUM) FORGE_VM_WASM_INTERPRET_CALL_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
           FORGE_VM_WASM_INTERPRET_CALL_IMM_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM) FORGE_VM_WASM_INTERPRET_PARAMETRIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
               FORGE_VM_WASM_INTERPRET_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                   FORGE_VM_WASM_INTERPRET_MEMORY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                       FORGE_VM_WASM_INTERPRET_I32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                           FORGE_VM_WASM_INTERPRET_I64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                               FORGE_VM_WASM_INTERPRET_F32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                   FORGE_VM_WASM_INTERPRET_F64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                       FORGE_VM_WASM_INTERPRET_COMPARISON_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                           FORGE_VM_WASM_INTERPRET_NUMERIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                               FORGE_VM_WASM_INTERPRET_CONVERSION_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                                   FORGE_VM_WASM_INTERPRET_EXIT_OP(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                                       FORGE_VM_WASM_INTERPRET_EMPTY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
                                                           FORGE_VM_WASM_INTERPRET_ERROR_OPS(FORGE_VM_WASM_INTERPRET_CREATE_ENUM)
};

struct opcode_utils {
   std::map<uint16_t, std::string> opcode_map{
       FORGE_VM_WASM_INTERPRET_CONTROL_FLOW_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP) FORGE_VM_WASM_INTERPRET_BR_TABLE_OP(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
           FORGE_VM_WASM_INTERPRET_RETURN_OP(FORGE_VM_WASM_INTERPRET_CREATE_MAP) FORGE_VM_WASM_INTERPRET_CALL_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
               FORGE_VM_WASM_INTERPRET_CALL_IMM_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                   FORGE_VM_WASM_INTERPRET_PARAMETRIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                       FORGE_VM_WASM_INTERPRET_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                           FORGE_VM_WASM_INTERPRET_MEMORY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                               FORGE_VM_WASM_INTERPRET_I32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                   FORGE_VM_WASM_INTERPRET_I64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                       FORGE_VM_WASM_INTERPRET_F32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                           FORGE_VM_WASM_INTERPRET_F64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                               FORGE_VM_WASM_INTERPRET_COMPARISON_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                                   FORGE_VM_WASM_INTERPRET_NUMERIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                                       FORGE_VM_WASM_INTERPRET_CONVERSION_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                                           FORGE_VM_WASM_INTERPRET_EXIT_OP(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                                               FORGE_VM_WASM_INTERPRET_EMPTY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)
                                                                   FORGE_VM_WASM_INTERPRET_ERROR_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MAP)};
};

enum imm_types {
   none,
   block_imm,
   varuint32_imm,
   br_table_imm,
};

FORGE_VM_WASM_INTERPRET_CONTROL_FLOW_OPS(FORGE_VM_WASM_INTERPRET_CREATE_CONTROL_FLOW_TYPES)
FORGE_VM_WASM_INTERPRET_BR_TABLE_OP(FORGE_VM_WASM_INTERPRET_CREATE_BR_TABLE_TYPE)
FORGE_VM_WASM_INTERPRET_RETURN_OP(FORGE_VM_WASM_INTERPRET_CREATE_CONTROL_FLOW_TYPES)
FORGE_VM_WASM_INTERPRET_CALL_OPS(FORGE_VM_WASM_INTERPRET_CREATE_CALL_TYPES)
FORGE_VM_WASM_INTERPRET_CALL_IMM_OPS(FORGE_VM_WASM_INTERPRET_CREATE_CALL_IMM_TYPES)
FORGE_VM_WASM_INTERPRET_PARAMETRIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)
FORGE_VM_WASM_INTERPRET_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_INTERPRET_CREATE_VARIABLE_ACCESS_TYPES)
FORGE_VM_WASM_INTERPRET_MEMORY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_MEMORY_TYPES)
FORGE_VM_WASM_INTERPRET_I32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_I32_CONSTANT_TYPE)
FORGE_VM_WASM_INTERPRET_I64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_I64_CONSTANT_TYPE)
FORGE_VM_WASM_INTERPRET_F32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_F32_CONSTANT_TYPE)
FORGE_VM_WASM_INTERPRET_F64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_CREATE_F64_CONSTANT_TYPE)
FORGE_VM_WASM_INTERPRET_COMPARISON_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)
FORGE_VM_WASM_INTERPRET_NUMERIC_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)
FORGE_VM_WASM_INTERPRET_CONVERSION_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)
FORGE_VM_WASM_INTERPRET_EXIT_OP(FORGE_VM_WASM_INTERPRET_CREATE_EXIT_TYPE)
FORGE_VM_WASM_INTERPRET_EMPTY_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)
FORGE_VM_WASM_INTERPRET_ERROR_OPS(FORGE_VM_WASM_INTERPRET_CREATE_TYPES)

using opcode =
    variant<FORGE_VM_WASM_INTERPRET_CONTROL_FLOW_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_BR_TABLE_OP(FORGE_VM_WASM_INTERPRET_IDENTITY)
                FORGE_VM_WASM_INTERPRET_RETURN_OP(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_CALL_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY)
                    FORGE_VM_WASM_INTERPRET_CALL_IMM_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_PARAMETRIC_OPS(
                        FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_VARIABLE_ACCESS_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY)
                        FORGE_VM_WASM_INTERPRET_MEMORY_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_I32_CONSTANT_OPS(
                            FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_I64_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY)
                            FORGE_VM_WASM_INTERPRET_F32_CONSTANT_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_F64_CONSTANT_OPS(
                                FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_COMPARISON_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY)
                                FORGE_VM_WASM_INTERPRET_NUMERIC_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_CONVERSION_OPS(
                                    FORGE_VM_WASM_INTERPRET_IDENTITY) FORGE_VM_WASM_INTERPRET_EXIT_OP(FORGE_VM_WASM_INTERPRET_IDENTITY)
                                    FORGE_VM_WASM_INTERPRET_EMPTY_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY)
                                        FORGE_VM_WASM_INTERPRET_ERROR_OPS(FORGE_VM_WASM_INTERPRET_IDENTITY_END)>;
} // namespace forge::vm::wasm::interpret
